-- 코드를 작성해주세요
WITH RECURSIVE generations AS (
    -- NON-RECURSION 문장(첫번째 루프에서만 실행)
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN generations G
    ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT, G.GENERATION
FROM generations G
WHERE NOT EXISTS(
SELECT 1
    FROM ECOLI_DATA CHILD
    WHERE CHILD.PARENT_ID = G.ID
)

GROUP BY G.GENERATION
ORDER BY G.GENERATION